### ISSUE TITLE
After the update for version 3.2.1, the buttons in the header are displayed in the mobile view.

### ISSUE THREAD

**Issue by ghost** [melvingb/we_universal#7]
After the update for version 3.2.1, the buttons in the header are displayed in the mobile view.

![file](https://user-images.githubusercontent.com/26491052/29614210-a6628dd0-8809-11e7-991e-e2fa0e081364.png)

**Comment by v12mike** [comment]
This change in behaviour was intentional, to make forum navigation quicker (no need to open the menu to find common options).
In order to fit the buttons on narrow screens, the button text is shortened, but the current settings might not be optimum for all languages.  The wrapping of the buttons will happen if you add extra buttons without removing others. 
Do you prefer to have the buttons removed, or adjusted so that they fit without wrapping?

**Comment by ghost** [comment]
I prefer to have the buttons removed

**Comment by Chocobo-ts** [comment]
We have same issue
![- 18 09 2017 - 16 15 53](https://user-images.githubusercontent.com/31732478/30543699-1e955766-9c95-11e7-9ca9-51fce6585154.png)

Please help us to hide these buttons
Thanks!

**Comment by Galixte** [comment]
Give me the link of your board, please?

**Comment by Galixte** [comment]
Hi @Chocobo-ts, share your board link to do some tests, please?

**Comment by Chocobo-ts** [comment]
Hi @Galixte, http://test.linuxmint.com.ru/
 style from this repo named **we_universal_lm**

**Comment by v12mike** [comment]
I have created a PR that makes it easy to configure whether the buttons or menu are shown in responsive mode.  I think that this should solve this issue.

See lines 75 and 94 of responsive.css

**Comment by Chocobo-ts** [comment]
@v12mike, it was so easy XD
Thanks a lot!
